# Schema for the configuration files of the api_logger module.
timing_monitor.settings:
  type: config_object
  label: 'Timing Monitor settings'
  mapping:
    row_limit:
      type: integer
      label: 'Timing Monitor messages to keep'
      constraints:
        NotNull: []
        AllowedValues: [0, 5, 100, 1000, 10000, 100000, 1000000]
    directory:
      type: string
      label: 'The directory, relative to public, to save the log files.'
      constraints:
        NotNull: []
    gzip:
      type: integer
      label: 'Whether or not to gzip the files.'
      constraints:
        NotNull: []
        AllowedValues: [0, 1]
    api:
      type: integer
      label: 'Enable api access to timing data.'
      constraints:
        NotNull: []
        AllowedValues: [0, 1]
