# Schema for the configuration files of the api_logger module.
timing_monitor.settings:
  type: config_object
  label: 'Timing Monitor settings'
  mapping:
    row_limit:
      type: integer
      label: 'Timing Monitor messages to keep'
    directory:
      type: string
      label: 'The directory, relative to public, to save the log files.'
    gzip:
      type: bool
      label: 'Whether or not to gzip the files.'
